### ISSUE TITLE
Support nodejs v21

### ISSUE THREAD

**Issue by hildjj** [homer0/jsdoc-ts-utils#42]
The engines setting makes node 21 fail:

https://github.com/homer0/jsdoc-ts-utils/blob/b845330bc4d9dc7dafafa456d3c231575830b79d/package.json#L42

**Comment by homer0** [comment]
@hildjj I'm so sorry it took me 5 months to reply, I think I marked the notification for the issue as read at some point and missed it.

I doubt it would be of any help at this point, but I never maintain stuff for edge versions, since they are not meant to be used in prod and I don't enough time to work on possible compatibility issues, sorry! You can install with `--ignore-engines` (or similar, depending on the client you are using).
